# Generated by Django 4.2.1 on 2023-05-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="middle_name",
            field=models.CharField(
                blank=True, default="", help_text="Middle Name(initial)", max_length=100
            ),
            preserve_default=False,
        ),
    ]
